--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2 (Debian 15.2-1.pgdg110+1)
-- Dumped by pg_dump version 15.1

-- Started on 2023-02-25 18:06:28 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 24728)
-- Name: CustomerRequests; Type: TABLE; Schema: public; Owner: server_admin
--

CREATE TABLE public."CustomerRequests" (
    "Id" integer NOT NULL,
    "RequestDate" timestamp with time zone NOT NULL,
    "RequestedQuantity" integer NOT NULL,
    "ShippingPrice" double precision NOT NULL,
    "PayementMethod" text NOT NULL,
    "CustomerId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Status" integer NOT NULL
);


ALTER TABLE public."CustomerRequests" OWNER TO server_admin;

--
-- TOC entry 219 (class 1259 OID 24727)
-- Name: CustomerRequests_Id_seq; Type: SEQUENCE; Schema: public; Owner: server_admin
--

ALTER TABLE public."CustomerRequests" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CustomerRequests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 24714)
-- Name: Customers; Type: TABLE; Schema: public; Owner: server_admin
--

CREATE TABLE public."Customers" (
    "Id" integer NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Mobile" text NOT NULL,
    "FixedLine" text NOT NULL,
    "Address" text NOT NULL,
    "BirthDate" timestamp with time zone NOT NULL,
    "UserInfoId" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Customers" OWNER TO server_admin;

--
-- TOC entry 217 (class 1259 OID 24713)
-- Name: Customers_Id_seq; Type: SEQUENCE; Schema: public; Owner: server_admin
--

ALTER TABLE public."Customers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Customers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 24705)
-- Name: Products; Type: TABLE; Schema: public; Owner: server_admin
--

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Price" double precision NOT NULL,
    "AvailableQuantity" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Products" OWNER TO server_admin;

--
-- TOC entry 215 (class 1259 OID 24704)
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: server_admin
--

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 40978)
-- Name: UserInfos; Type: TABLE; Schema: public; Owner: server_admin
--

CREATE TABLE public."UserInfos" (
    "Id" integer NOT NULL,
    "UserName" text NOT NULL,
    "Password" text NOT NULL,
    "Email" text NOT NULL,
    "CreatedDate" text NOT NULL
);


ALTER TABLE public."UserInfos" OWNER TO server_admin;

--
-- TOC entry 221 (class 1259 OID 40977)
-- Name: UserInfo_Id_seq; Type: SEQUENCE; Schema: public; Owner: server_admin
--

ALTER TABLE public."UserInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserInfo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 24699)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: server_admin
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO server_admin;

--
-- TOC entry 3207 (class 2606 OID 24734)
-- Name: CustomerRequests PK_CustomerRequests; Type: CONSTRAINT; Schema: public; Owner: server_admin
--

ALTER TABLE ONLY public."CustomerRequests"
    ADD CONSTRAINT "PK_CustomerRequests" PRIMARY KEY ("Id");


--
-- TOC entry 3203 (class 2606 OID 24720)
-- Name: Customers PK_Customers; Type: CONSTRAINT; Schema: public; Owner: server_admin
--

ALTER TABLE ONLY public."Customers"
    ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("Id");


--
-- TOC entry 3200 (class 2606 OID 24711)
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: server_admin
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- TOC entry 3209 (class 2606 OID 40992)
-- Name: UserInfos PK_UserInfos; Type: CONSTRAINT; Schema: public; Owner: server_admin
--

ALTER TABLE ONLY public."UserInfos"
    ADD CONSTRAINT "PK_UserInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3198 (class 2606 OID 24703)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: server_admin
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3204 (class 1259 OID 24745)
-- Name: IX_CustomerRequests_CustomerId; Type: INDEX; Schema: public; Owner: server_admin
--

CREATE INDEX "IX_CustomerRequests_CustomerId" ON public."CustomerRequests" USING btree ("CustomerId");


--
-- TOC entry 3205 (class 1259 OID 24746)
-- Name: IX_CustomerRequests_ProductId; Type: INDEX; Schema: public; Owner: server_admin
--

CREATE INDEX "IX_CustomerRequests_ProductId" ON public."CustomerRequests" USING btree ("ProductId");


--
-- TOC entry 3201 (class 1259 OID 40985)
-- Name: IX_Customers_UserInfoId; Type: INDEX; Schema: public; Owner: server_admin
--

CREATE INDEX "IX_Customers_UserInfoId" ON public."Customers" USING btree ("UserInfoId");


--
-- TOC entry 3211 (class 2606 OID 24735)
-- Name: CustomerRequests FK_CustomerRequests_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: server_admin
--

ALTER TABLE ONLY public."CustomerRequests"
    ADD CONSTRAINT "FK_CustomerRequests_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3212 (class 2606 OID 24740)
-- Name: CustomerRequests FK_CustomerRequests_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: server_admin
--

ALTER TABLE ONLY public."CustomerRequests"
    ADD CONSTRAINT "FK_CustomerRequests_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;


--
-- TOC entry 3210 (class 2606 OID 40993)
-- Name: Customers FK_Customers_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: server_admin
--

ALTER TABLE ONLY public."Customers"
    ADD CONSTRAINT "FK_Customers_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


-- Completed on 2023-02-25 18:06:28 UTC

--
-- PostgreSQL database dump complete
--
